#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.
set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

PROJECT_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export PROJECT_ROOT

echo "==> Running tests…"
python3 -m unittest discover
